Drop package BWTA_METADATA;
Drop package BWTA_OPER;
Drop package BWTA_THREAD;
Drop table BWTA_HEAP cascade constraints;
Drop table BWTA_TASK cascade constraints;
Drop table BWTA_TASK_REL cascade constraints;
Drop table BWTA_RES cascade constraints;
Drop table BWTA_TASK_RES cascade constraints;
Drop table BWTA_ERR cascade constraints;
Drop table BWTA_LOG_ROUND cascade constraints;
Drop table BWTA_LOG_PROC cascade constraints;
Drop table BWTA_LOG_PROC_H cascade constraints;
Drop table BWTA_LOG_THREAD cascade constraints;
Drop table BWTA_LOG_ERR cascade constraints;
Drop table BWTA_LOG_METADATA cascade constraints;
Drop sequence BWTA_HEAP_SEQ;
Drop sequence BWTA_TASK_SEQ;
Drop sequence BWTA_RES_SEQ;
Drop sequence BWTA_LOG_ROUND_SEQ;
Drop sequence BWTA_LOG_THREAD_SEQ;
Drop View BWTA_V_LOG_TASK_WIDE;
